import * as fs from 'fs';
import * as path from 'path';

const AUDIO_DIR = path.join(__dirname, '..', 'public', 'audio');
const MANIFEST_PATH = path.join(__dirname, '..', 'src', 'data', 'audio-manifest.ts');

const audioFiles: string[] = [];

try {
  if (fs.existsSync(AUDIO_DIR)) {
    for (const file of fs.readdirSync(AUDIO_DIR)) {
      if (file.endsWith('.wav')) {
        audioFiles.push(file.replace('.wav', ''));
      }
    }
  }
} catch {
  // No audio directory
}

const content = `// Auto-generated file - lists available audio files in public/audio/
// Regenerated by scripts/scan-audio.ts before render
export const AVAILABLE_AUDIO: string[] = ${JSON.stringify(audioFiles, null, 2)};
`;

fs.writeFileSync(MANIFEST_PATH, content);
console.log(`Audio manifest: ${audioFiles.length} files found`);
if (audioFiles.length > 0) {
  console.log(`  ${audioFiles.join(', ')}`);
}
