import * as fs from 'fs';
import * as path from 'path';

const IMAGE_DIR = path.join(__dirname, '..', 'public', 'images');
const MANIFEST_PATH = path.join(__dirname, '..', 'src', 'data', 'image-manifest.ts');

const imageFiles: string[] = [];

try {
  if (fs.existsSync(IMAGE_DIR)) {
    for (const file of fs.readdirSync(IMAGE_DIR)) {
      if (file.endsWith('.png') || file.endsWith('.jpg') || file.endsWith('.webp')) {
        imageFiles.push(file.replace(/\.(png|jpg|webp)$/, ''));
      }
    }
  }
} catch {
  // No image directory
}

const content = `// Auto-generated - lists available slide images in public/images/
// Regenerated by scripts/scan-images.ts before render
export const AVAILABLE_IMAGES: string[] = ${JSON.stringify(imageFiles, null, 2)};
`;

fs.writeFileSync(MANIFEST_PATH, content);
console.log(`Image manifest: ${imageFiles.length} files found`);
if (imageFiles.length > 0) {
  console.log(`  ${imageFiles.join(', ')}`);
}
